image: gradle:jdk17-focal

before_script:
  - chmod +x ./gradlew
  - wget "https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip"
  - unzip BrowserStackLocal-linux-x64.zip
  - ./BrowserStackLocal --key $BROWSERSTACK_ACCESS_KEY --daemon start

build:
  stage: build
  script:
    - gradle build -x test

test:
  stage: test
  script:
    - gradle test
    - ./BrowserStackLocal --key $BROWSERSTACK_ACCESS_KEY --daemon stop